# Generated by Django 4.1.5 on 2023-05-01 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('isdCode', models.CharField(max_length=5)),
                ('mobile', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaHandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('linkedIn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('featured_image', models.ImageField(upload_to='blogFeaturedImages/')),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cuser')),
            ],
        ),
    ]
