# Generated by Django 4.1.5 on 2023-05-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='featured_image',
            field=models.ImageField(upload_to='static/img/blogFeaturedImages/'),
        ),
    ]
