# Generated by Django 4.1.5 on 2023-05-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_posts_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='bio',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
    ]
