# Generated by Django 4.1.5 on 2023-05-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_socialmediahandles_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediahandles',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediahandles',
            name='linkedIn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediahandles',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
