# Generated by Django 4.1.5 on 2023-05-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_socialmediahandles_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='featured_image',
            field=models.ImageField(upload_to='Images/'),
        ),
    ]
