# Generated by Django 4.1.5 on 2023-05-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_posts_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='author_image',
            field=models.ImageField(default='', null=True, upload_to='Images/author/'),
        ),
    ]
