# Generated by Django 4.1.5 on 2023-05-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_cuser_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='author_image',
            field=models.ImageField(default='default_author.jpg', null=True, upload_to='Images/author/'),
        ),
    ]
