# Generated by Django 4.1.5 on 2023-05-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_cuser_author_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmediahandles',
            old_name='linkedIn',
            new_name='linkedin',
        ),
    ]
