# Generated by Django 4.1.5 on 2023-05-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_linkedin_socialmediahandles_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediahandles',
            name='github',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialmediahandles',
            name='medium',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
