# Generated by Django 4.1.5 on 2023-05-04 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_socialmediahandles_github_socialmediahandles_medium'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuser',
            new_name='Author',
        ),
    ]
