# Generated by Django 4.1.5 on 2023-05-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_cuser_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='medium_url',
            field=models.URLField(default='https://medium.com/@chanchalkmaurya'),
            preserve_default=False,
        ),
    ]
